import os
from pathlib import Path

# Base Paths
BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
INDEX_DIR = BASE_DIR / "indexes"

# Ensure directories exist
DATA_DIR.mkdir(parents=True, exist_ok=True)
INDEX_DIR.mkdir(parents=True, exist_ok=True)

# Model Settings
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
RERANK_MODEL_NAME = "cross-encoder/ms-marco-MiniLM-L-6-v2"
SPACY_MODEL_NAME = "en_core_web_sm"

# Chunking Configuration
DEFAULT_CHUNK_SIZE = 600       # Target chunk size in characters
DEFAULT_CHUNK_OVERLAP = 120    # Overlap between chunks
SEMANTIC_SPLIT_THRESHOLD = 0.55 # Cosine similarity threshold below which a split is triggered

# Retrieval Settings
RETRIEVAL_TOP_K = 25  # Number of raw chunks to retrieve per search method

# RRF Configuration
RRF_K = 60            # Constant for Reciprocal Rank Fusion
# Weights for sparse, dense, and graph-based retrieval scores
RRF_WEIGHTS = {
    "sparse": 0.35,   # Weight for BM25
    "dense": 0.45,    # Weight for Sentence Embeddings
    "graph": 0.20     # Weight for Knowledge Graph Entity matches
}

# Reranker Settings
RERANK_TOP_K = 15     # Number of candidate chunks to pass to the cross-encoder
FINAL_TOP_K = 5       # Final number of results to return to the user

# Extractive Summarization Configuration
SUMMARY_SENTENCES_COUNT = 3  # Number of sentences to extract for the summary

# =====================================================================
# TEEP 2026 FINANCIAL NLP & ANNUAL REPORT EXTENSIONS
# =====================================================================

# SEC Annual Report (Form 10-K / 10-Q) Section Mapping
SEC_SECTIONS = {
    "ITEM_1": {"code": "Item 1", "title": "Business", "keywords": ["item 1.", "item 1 - business", "business overview"]},
    "ITEM_1A": {"code": "Item 1A", "title": "Risk Factors", "keywords": ["item 1a.", "item 1a - risk factors", "risk factors"]},
    "ITEM_1B": {"code": "Item 1B", "title": "Unresolved Staff Comments", "keywords": ["item 1b.", "unresolved staff comments"]},
    "ITEM_2": {"code": "Item 2", "title": "Properties", "keywords": ["item 2.", "properties"]},
    "ITEM_3": {"code": "Item 3", "title": "Legal Proceedings", "keywords": ["item 3.", "legal proceedings"]},
    "ITEM_7": {"code": "Item 7", "title": "Management's Discussion and Analysis (MD&A)", "keywords": ["item 7.", "item 7 - management", "management's discussion and analysis"]},
    "ITEM_7A": {"code": "Item 7A", "title": "Quantitative and Qualitative Disclosures About Market Risk", "keywords": ["item 7a.", "quantitative and qualitative disclosures"]},
    "ITEM_8": {"code": "Item 8", "title": "Financial Statements and Supplementary Data", "keywords": ["item 8.", "financial statements and supplementary data", "consolidated balance sheets"]},
    "ITEM_9A": {"code": "Item 9A", "title": "Controls and Procedures", "keywords": ["item 9a.", "controls and procedures"]},
    "NOTES": {"code": "Notes", "title": "Notes to Consolidated Financial Statements", "keywords": ["notes to consolidated", "note 1", "note 2"]}
}

# Standardized Financial Metrics Schema
FINANCIAL_METRICS_SCHEMA = {
    "revenue": {
        "display_name": "Total Revenue / Net Sales",
        "category": "Income Statement",
        "synonyms": ["total net sales", "revenue", "total revenue", "net revenues", "sales", "operating revenues"],
        "unit": "USD"
    },
    "cogs": {
        "display_name": "Cost of Goods Sold (COGS)",
        "category": "Income Statement",
        "synonyms": ["cost of sales", "cost of goods sold", "cost of revenues", "total cost of sales"],
        "unit": "USD"
    },
    "gross_profit": {
        "display_name": "Gross Profit",
        "category": "Income Statement",
        "synonyms": ["gross profit", "gross margin $"],
        "unit": "USD"
    },
    "operating_income": {
        "display_name": "Operating Income (EBIT)",
        "category": "Income Statement",
        "synonyms": ["operating income", "operating profit", "income from operations"],
        "unit": "USD"
    },
    "net_income": {
        "display_name": "Net Income",
        "category": "Income Statement",
        "synonyms": ["net income", "net earnings", "net profit", "net income attributable to shareholders"],
        "unit": "USD"
    },
    "eps_diluted": {
        "display_name": "Diluted Earnings Per Share (EPS)",
        "category": "Per Share",
        "synonyms": ["diluted earnings per share", "earnings per share - diluted", "diluted eps", "diluted net income per share"],
        "unit": "USD/Share"
    },
    "operating_cash_flow": {
        "display_name": "Cash Flow from Operations",
        "category": "Cash Flow",
        "synonyms": ["cash generated by operating activities", "net cash provided by operating activities", "cash from operations"],
        "unit": "USD"
    },
    "capex": {
        "display_name": "Capital Expenditures (CapEx)",
        "category": "Cash Flow",
        "synonyms": ["capital expenditures", "payments for property, plant and equipment", "additions to property"],
        "unit": "USD"
    },
    "free_cash_flow": {
        "display_name": "Free Cash Flow (FCF)",
        "category": "Cash Flow",
        "synonyms": ["free cash flow"],
        "unit": "USD"
    },
    "total_debt": {
        "display_name": "Total Debt",
        "category": "Balance Sheet",
        "synonyms": ["total debt", "short-term and long-term debt", "commercial paper and term debt", "total liabilities"],
        "unit": "USD"
    },
    "cash_and_equivalents": {
        "display_name": "Cash and Cash Equivalents",
        "category": "Balance Sheet",
        "synonyms": ["cash and cash equivalents", "cash, cash equivalents, and marketable securities"],
        "unit": "USD"
    }
}

# Loughran-McDonald Financial Sentiment Lexicon Categories
# (Curated domain-specific vocabulary for financial text analysis)
LOUGHRAN_MCDONALD_LEXICON = {
    "negative": [
        "loss", "losses", "decline", "declined", "declining", "adverse", "adversely",
        "impairment", "restructuring", "deterioration", "defect", "deficit", "default",
        "breach", "litigation", "investigation", "penalty", "discontinued", "downward",
        "insolvency", "bankruptcy", "violation", "recession", "volatility", "unfavorable",
        "terminated", "termination", "damage", "damages", "write-down", "writedown",
        "slowdown", "curtailment", "distress", "subpoena", "sanction", "turmoil"
    ],
    "positive": [
        "growth", "profit", "profitable", "gain", "gains", "improvement", "improved",
        "favorable", "benefit", "benefited", "exceeded", "outperformed", "achieved",
        "success", "successful", "strengthen", "strengthened", "robust", "resilient",
        "expansion", "efficient", "efficiency", "momentum", "record", "optimistic",
        "competitive", "opportunity", "opportunities", "innovative", "synergy"
    ],
    "uncertainty": [
        "approximate", "approximately", "assume", "assumes", "assumption", "assumptions",
        "contingent", "contingency", "could", "depend", "dependent", "fluctuate",
        "fluctuating", "indefinite", "instability", "may", "might", "possible", "possibly",
        "potential", "potentially", "predict", "predicted", "risk", "risks", "uncertain",
        "uncertainty", "uncertainties", "variable", "variability", "estimate", "estimates"
    ],
    "litigious": [
        "claim", "claims", "dispute", "disputes", "injunction", "arbitration", "lawsuit",
        "lawsuits", "settlement", "settled", "litigation", "court", "complaint", "legal",
        "legislation", "regulatory", "compliance", "allegation", "alleges", "indemnify",
        "indemnification", "jurisdiction", "proceeding", "proceedings"
    ],
    "constraining": [
        "commit", "commitment", "commitments", "covenant", "covenants", "require",
        "requires", "required", "obligation", "obligations", "restricted", "restriction",
        "prohibit", "prohibits", "prohibited", "limit", "limits", "limitation", "mandate",
        "mandated", "binding", "strictly"
    ]
}

# Financial Query Expansion & Synonym Mappings
FINANCIAL_QUERY_EXPANSION = {
    "profitability": ["operating margin", "gross margin", "net income", "operating income", "EBITDA", "return on assets"],
    "revenue": ["net sales", "top line", "operating revenue", "turnover", "total net sales"],
    "risk": ["risk factors", "Item 1A", "uncertainty", "contingency", "supply chain disruption", "regulatory risk", "cybersecurity"],
    "debt": ["leverage", "total liabilities", "credit facility", "maturities", "commercial paper", "borrowings"],
    "liquidity": ["cash and cash equivalents", "marketable securities", "operating cash flow", "working capital"],
    "strategy": ["business overview", "Item 1", "strategic priorities", "research and development", "market expansion"],
    "guidance": ["forward-looking statements", "outlook", "management's discussion", "Item 7", "MD&A trends"]
}

# Evaluation Suite Configurations
EVALUATION_TOP_KS = [3, 5, 10]
BENCHMARK_DIR = BASE_DIR / "benchmarks"
BENCHMARK_DIR.mkdir(parents=True, exist_ok=True)

